name: project proposal
description: VRS Hackathon Project Proposal
title: "[Project title]"
labels: project proposal
assignees: ''

body:
  - type: input
    id: submitter_name
    attributes:
      label: Submitter Name
      placeholder: John Doe
    validations:
      required: true
  - type: input
    id: submitter_affiliation
    attributes:
      label: Submitter Affiliation
      placeholder: ABC Institution
    validations:
      required: false
  - type: input
    id: submitter_githubid
    attributes:
      label: Submitter Github Handle
      placeholder: johndoe999
    validations:
      required: true
  - type: textarea
    id: submitter_additional
    attributes:
      label: Additional Submitter Details
      placeholder: 
  - type: checkboxes
    id: event_days
    attributes:
      label: On which event days would the project be offered?
      description: You may select more than one.
      options:
        - label: ISMB 2022 Hackathon Day 1
        - label: ISMB 2022 Hackathon Day 2
    validations:
      required: true
  - type: markdown
    id: project_details
    attributes:
      label: Project Details
      description: Discuss what the project intends to accomplish and how it improves the use of VRS
    validations:
      required: true
  - type: markdown
    id: required_skills
    attributes:
      label: Required Skills
      description: List any skillset necessary or beneficial for participants to contribute to the project, e.g. Python, reStructuredText, Rust, UML
